---
- name: Install deb822 dependency
  ansible.builtin.apt:
    name: python3-debian
    state: present

- name: Add Docker repository
  ansible.builtin.deb822_repository:
    name: docker
    types:
      - deb
    uris: https://download.docker.com/linux/ubuntu
    suites:
      - "{{ ansible_facts['distribution_release'] }}"
    components:
      - stable
    architectures:
      - "{{ docker_arch_map[ansible_facts['architecture']] }}"
    signed_by: https://download.docker.com/linux/ubuntu/gpg
    state: present
  register: docker_repo

- name: Update apt cache after adding Docker repository
  ansible.builtin.apt:
    update_cache: true
  when: docker_repo.changed

- name: Install Docker packages
  ansible.builtin.apt:
    name: "{{ docker_packages }}"
    state: present

- name: Enable and start Docker
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true