---
- name: Common Setup
  hosts: all
  become: true
  roles:
    - common

- name: Nginx Setup
  hosts: nginx
  become: true
  roles:
    - nginx
  tags:
    - nginx

- name: Backend Setup
  hosts: backend
  become: true
  roles:
    - backend
    - docker
  tags:
    - backend

- name: Docker Setup
  hosts: backend
  become: true
  roles:
    - docker
  tags:
    - docker